deployUrl=file:///Users/cer/.m2/testdeploy

dockerImageTag=latest

eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

springBootVersion=4.1.1

junitVersion=6.0.3
junitPlatformLauncherVersion=6.0.3

mockitoVersion=5.23.0

springCloudContractDependenciesVersion=2.0.0.RELEASE
springDependencyManagementPluginVersion=1.0.3.RELEASE
dockerComposePluginVersion=0.17.7
eventuateUtilVersion=0.20.0.BUILD-SNAPSHOT
eventuateTramVersion=0.38.0.BUILD-SNAPSHOT
eventuateLocalVersion=0.45.0.BUILD-SNAPSHOT
eventuateCommonImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateCdcImageVersion=0.20.0.BUILD-SNAPSHOT
eventuateCommonVersion=0.22.0.BUILD-SNAPSHOT
eventuatePluginsGradleVersion=0.15.0.BUILD-SNAPSHOT
eventuateMessagingKafkaImageVersion=0.22.0.BUILD-SNAPSHOT
micronautVersion=2.4.1

reactorVersion=3.8.3
h2Version=2.4.240
jakartaAnnotationApiVersion=3.0.0
jakartaPersistenceApiVersion=3.2.0
mysqlConnectorVersion=9.7.0
postgresqlVersion=42.7.13

version=0.27.0-SNAPSHOT
